on:
  workflow_call:

jobs:
  build:
    name: Run pa11y test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Set up prerequisites - node and yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Cache yarn dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Build
        run: yarn run build

      - name: Run pa11y
        run: yarn run pa11y-ci
        continue-on-error: true

      - name: Send pa11y results to PR Comment
        uses: actions/github-script@v7
        env:
          BODY_PREFIX: '<!-- pa11y-ci results -->'
          OWNER: 'johnnolan'
          REPO: 'dnd-vlendir-campaign'
        with:
          script: |
            const script = require('./.github/workflows/scripts/pa11y-ci.js')
            await script({ github, context, core })
